### ISSUE TITLE
.ExportToKML   coordinates with conversion error

### ISSUE THREAD

**Issue by geodrinx** [JuergenWeichand/qgis-geometry-exporter-plugin#2]
Using  SRs  other than 4326, KML coordinates are wrong.

An example: 

epsg:3003
LINESTRING (1882514.1528254398 4572254.977329189,1882732.8061865449 4572531.1017223522,1882642.203243443 4572605.9037163248,1882912.6082268576 4572663.4021606883,1882958.6035382384 4572418.8877489008,1882875.1893943013 4572472.1145593831,1882665.1692695501 4572224.7548517529)

ogr.ExportToKML   returns this:

<LineString><coordinates>74.152825439814478,4572254.977329189 -67.193813455058262,4572531.1017223522 -157.7967565569561,4572605.9037163248 112.60822685761377,4572663.4021606883 158.60353823844343,4572418.8877489008 75.189394301269203,4572472.1145593831 -134.83073044987395,4572224.7548517529</coordinates></LineString>

Perhaps, is this an   OGR  error ?

**Comment by JuergenWeichand** [comment]
Thanks for reporting. 
Using `QGIS 2.14` with `GDAL 2.0.2` ogr.ExportToKML fails completely.

```
Traceback (most recent call last):
              File "C:/Users/wei/.qgis2/python/plugins\GeometryExporter\geometry_exporter.py", line 277, in populate
                export = geom.ExportToKML()
              File "C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\osgeo\ogr.py", line 4254, in ExportToKML
                return _ogr.Geometry_ExportToKML(self, *args)
            SystemError: error return without exception set
```
